services:
  - type: web
    name: task-manager-node-api
    runtime: node
    plan: free
    buildCommand: npm run build-node
    startCommand: npm run start-node
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager-db
          property: connectionString

  - type: web
    name: task-manager-python-api
    runtime: python
    plan: free
    buildCommand: npm run build-python
    startCommand: npm run start-python
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: task-manager-db
    plan: free